package model.enums;

public enum TiposDeServicos {
  LAVAGEM_SIMPLES,
  LAVAGEM_DETALHADA,
  POLIMENTO_TECNICO,
  PPF,
  INSULFILM,
  DESCONTAMINACAO_PINTURA,
  RENOVACAO_ESTOFADOS,
  LIMPEZA_DA_QUINTA_RODA,
  LAVAGEM_CARRETA,
  POLIMENTO_TECNICO_CARRETA;
  
}
